name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MonoGame CLI tool
      run: |
        dotnet tool install --global dotnet-mgcb-editor-linux --version 3.8.4.1 || dotnet tool update --global dotnet-mgcb-editor-linux --version 3.8.4.1
        export PATH="$HOME/.dotnet/tools:$PATH"
        dotnet tool list --global
        mgcb --help

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
